### ISSUE TITLE
HwhFrontend doesn't register interrupt ports

### ISSUE THREAD

**Issue by TRnhld** [Xilinx/PYNQ-Metadata#15]
In [hwh_frontend.py](../blob/main/pynqmetadata/frontends/hwh_frontend.py) there is no check for type of `INTERRUPT` scalar port.

The Parser registers scalar port types of "rst" and "clk". (line 336f. for external and line 432 for internal signals)
There should also be a check for ` if p.get("SIGIS") == "INTERRUPT"`.

**Comment by STFleming** [comment]
Thanks for raising this! However, I think I might need a bit more details on this issue.

As it stands interrupt lines are figured out when constructing the interrupt dict view onto the metadata. It walks backwards from interrupt controller IP into the PS. This means that currently interrupts are treated like regular scalar ports when parsing the hwh. We could add an extra port type for interrupt like we have for clk and rst, but it would be good to understand if there is a specific bug that triggered this request.

**Comment by TRnhld** [comment]
I need to have a look further into this to provide more information.
So far i noticed, there is a difference of connecting the concatinated interrupts directly to the IRQ_F2P Port of Zynq-PS (empty list of interrupts in overlay object) and using an interrupt controller (some interrupts are registered).

I'll update this issue as I find out further information.
